name: Cloud Functions Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          project_id: 'react-translate-app-410021'
          workload_identity_provider: 'projects/577940326996/locations/global/workloadIdentityPools/my-workload-identity-pool/providers/my-workload-provider'
          service_account: 'mySAnicklin@react-translate-app-410021.iam.gserviceaccount.com'
      # https://github.com/google-github-actions/setup-gcloud
      # https://github.com/google-github-actions/auth#setting-up-workload-identity-federation

      - name: 設定 Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 建立 GCF 環境變數檔案
        shell: bash
        run: |
          [[ -z "$ENV_PROD" ]] || echo "$ENV_PROD" > .env.yaml
          echo "GITHUB_SHA: ${GITHUB_SHA}" >> .env.yaml
        env:
          ENV_PROD: ${{ secrets.ENV_PROD }}
      # https://cloud.google.com/functions/docs/deploy
      # 請在這個網頁查看自動佈署的參數說明

      - id: 'upload-file'
        name: '上傳檔案到Google Cloud Storage'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './'
          destination: 'gcf_static/leafrainsuns'

      # - id: 'deploy'
      #   name: 部署到 Google Cloud Functions
      #   uses: 'google-github-actions/deploy-cloud-functions@v2'
      #   with:
      #     name: 'leafrainsuns'
      #     runtime: 'nodejs20'
      #     entry_point: 'callback'
      #     memory_mb: '128Mi'
      #     region: 'asia-east1'
      #     env_vars_file: '.env.yaml'
      #     max_instances: 1

      - name: 部署到 Google Cloud Functions
        run: >-
          gcloud functions deploy leafrainsuns --allow-unauthenticated --entry-point=callback --env-vars-file=.env.yaml --gen2 --max-instances=1 --memory=128Mi --no-user-output-enabled --region=asia-east1 --runtime=nodejs20 --timeout=60s --trigger-http
